[package]
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
name = "netlink-sys"
version = "0.2.0"
edition = "2018"

homepage = "https://github.com/little-dude/netlink"
keywords = ["netlink", "ip", "linux"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/little-dude/netlink"
description = "netlink sockets, with optional integration with mio and tokio"

[dependencies]
libc = "0.2"
log = "0.4"

[dependencies.futures]
optional = true
version = "0.3.0"

[dependencies.mio]
optional = true
version = "0.6"

[dependencies.tokio]
optional = true
version = "0.2"
features = ["io-driver"]

[features]
default = []
mio_socket = ["mio"]
tokio_socket = ["mio_socket", "tokio", "futures"]

[dev-dependencies]
tokio = { version = "0.2.0", features = ["full"] }
netlink-packet-audit = { path = "../netlink-packet-audit" }

[[example]]
name = "audit_events"

[[example]]
name = "audit_events_async"
required-features = ["tokio_socket"]